---
terraform_repo_url: "https://apt.releases.hashicorp.com"
terraform_gpg_url: "https://apt.releases.hashicorp.com/gpg"
terraform_keyring_path: "/etc/apt/keyrings/hashicorp.asc"
terraform_package: terraform
