---
- name: Installer la toolbox DevOps
  hosts: all
  become: true
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/{{ toolbox_env }}.yml
  roles:
    - role: common
    - role: docker
      when: toolbox_install.docker | default(false)
    - role: terraform
      when: toolbox_install.terraform | default(false)
